--- asterisk/channels/Makefile.orig	2010-06-08 02:04:42.000000000 +0600
+++ asterisk/channels/Makefile	2012-11-21 17:45:02.000000000 +0600
@@ -21,14 +21,14 @@
 endif
 
 ifeq ($(OSARCH),linux-gnu)
-  PTLIB=-lpt_linux_x86_r
-  H323LIB=-lh323_linux_x86_r
+  PTLIB=-lpt_d
+  H323LIB=-lh323_linux_x86__d
   CHANH323LIB=-ldl
 endif
 
 ifeq ($(OSARCH),FreeBSD)
-  PTLIB=-lpt_FreeBSD_x86_r
-  H323LIB=-lh323_FreeBSD_x86_r
+  PTLIB=-lpt_d
+  H323LIB=-lh323_FreeBSD_x86__d
   CHANH323LIB=-pthread
 endif
 
@@ -57,17 +57,18 @@
   LIBS+= -lres_monitor.so -lres_features.so
 endif
 
-ifneq ($(wildcard h323/Makefile.ast),)
+ifeq ($(wildcard h323/chan_h323.so),)
 include h323/Makefile.ast
 endif
 
 clean::
 	$(MAKE) -C misdn clean
 	rm -f sip/*.o sip/*.i
-	rm -f h323/libchanh323.a h323/Makefile.ast h323/*.o h323/*.dep
+	gmake -C h323 clean
 
 dist-clean::
-	rm -f h323/Makefile
+	gmake -C h323 dist-clean
+	rm -f Makefile
 
 $(if $(filter chan_iax2,$(EMBEDDED_MODS)),modules.link,chan_iax2.so): iax2-parser.o iax2-provision.o
 iax2-parser.o iax2-provision.o: _ASTCFLAGS+=$(call MOD_ASTCFLAGS,chan_iax2)
@@ -79,15 +80,10 @@
 ifneq ($(filter chan_h323,$(EMBEDDED_MODS)),)
 modules.link: h323/libchanh323.a
 else
-ifeq ($(OSARCH),linux-gnu)
 chan_h323.so: chan_h323.o h323/libchanh323.a
 	$(ECHO_PREFIX) echo "   [LD] $^ -> $@"
-	$(CMD_PREFIX) $(CXX) $(PTHREAD_CFLAGS) $(_ASTLDFLAGS) $(ASTLDFLAGS) $(SOLINK) -o $@ $< h323/libchanh323.a $(H323LDLIBS)
-else
-chan_h323.so: chan_h323.o h323/libchanh323.a
-	$(ECHO_PREFIX) echo "   [LD] $^ -> $@"
-	$(CMD_PREFIX) $(CXX) $(PTHREAD_CFLAGS) $(_ASTLDFLAGS) $(ASTLDFLAGS) $(SOLINK) -o $@ $< h323/libchanh323.a $(CHANH323LIB) -L$(PWLIBDIR)/lib $(PTLIB) -L$(OPENH323DIR)/lib $(H323LIB) -L/usr/lib -lcrypto -lssl -lexpat
-endif
+	$(ECHO_PREFIX) echo "$(CMD_PREFIX) $(CXX) $(PTHREAD_CFLAGS) $(_ASTLDFLAGS) $(ASTLDFLAGS) $(SOLINK) $(H323CFLAGS) $(H323LDFLAGS) $(H323LDLIBS) -o $@ $< h323/libchanh323.a"
+	$(CMD_PREFIX) $(CXX) $(PTHREAD_CFLAGS) $(_ASTLDFLAGS) $(ASTLDFLAGS) $(SOLINK) $(H323CFLAGS) $(H323LDFLAGS) $(H323LDLIBS) -o $@ $< h323/libchanh323.a
 endif
 
 chan_misdn.o: _ASTCFLAGS+=-Imisdn
