--- opensips/Makefile.orig	2012-09-09 16:09:04.000000000 +0600
+++ opensips/Makefile	2012-10-16 10:56:10.000000000 +0600
@@ -480,17 +480,17 @@
 # note: on solaris 8 sed: ? or \(...\)* (a.s.o) do not work
 install-cfg: $(cfg-prefix)/$(cfg-dir)
 		sed -e "s#/usr/.*lib/$(NAME)/modules/#$(modules-target)#g" \
-			< etc/$(NAME).cfg > $(cfg-prefix)/$(cfg-dir)$(NAME).cfg.sample0
+			< etc/$(NAME).cfg > $(cfg-prefix)/$(cfg-dir)/$(NAME).cfg.sample0
 		sed -e "s#/usr/.*etc/$(NAME)/tls/#$(cfg-target)tls/#g" \
-			< $(cfg-prefix)/$(cfg-dir)$(NAME).cfg.sample0 \
-			> $(cfg-prefix)/$(cfg-dir)$(NAME).cfg.sample
-		rm -fr $(cfg-prefix)/$(cfg-dir)$(NAME).cfg.sample0
-		chmod 600 $(cfg-prefix)/$(cfg-dir)$(NAME).cfg.sample
+			< $(cfg-prefix)/$(cfg-dir)/$(NAME).cfg.sample0 \
+			> $(cfg-prefix)/$(cfg-dir)/$(NAME).cfg.sample
+		rm -fr $(cfg-prefix)/$(cfg-dir)/$(NAME).cfg.sample0
+		chmod 600 $(cfg-prefix)/$(cfg-dir)/$(NAME).cfg.sample
 		chmod 700 $(cfg-prefix)/$(cfg-dir)
 		if [ -z "${skip_cfg_install}" -a \
-				! -f $(cfg-prefix)/$(cfg-dir)$(NAME).cfg ]; then \
-			mv -f $(cfg-prefix)/$(cfg-dir)$(NAME).cfg.sample \
-				$(cfg-prefix)/$(cfg-dir)$(NAME).cfg; \
+				! -f $(cfg-prefix)/$(cfg-dir)/$(NAME).cfg ]; then \
+			mv -f $(cfg-prefix)/$(cfg-dir)/$(NAME).cfg.sample \
+				$(cfg-prefix)/$(cfg-dir)/$(NAME).cfg; \
 		fi
 		# radius dictionary
 		if [ "$(RADIUSDEPON)" = "yes" ]; then \
